import type { Garment } from "./types";

/**
 * Preview-only catalog shown on /discover when the real backend can't be
 * reached (see app/(shop)/discover/page.tsx) — lets the product-card design
 * be reviewed without a live API. Never used when the real fetch succeeds.
 */
export const MOCK_GARMENTS: Garment[] = [
  {
    id: "mock-ivory-slip-dress",
    name: "Ivory Satin Slip Dress",
    brand: "Étoile",
    category: "Dresses",
    occasions: ["Party", "Date Night"],
    styles: ["Minimal", "Classic"],
    color: "Ivory",
    colorHex: "#E9E1D2",
    conditionCopy: "Excellent condition, inspected before dispatch",
    currency: "INR",
    rentPrice: 1499,
    rentDays: 4,
    buyPrice: 6999,
    deposit: 1000,
    sizes: [
      { size: "XS", available: true },
      { size: "S", available: true },
      { size: "M", available: true },
      { size: "L", available: false },
    ],
    availability: "available",
    availableFrom: "Today",
    deliveryDays: 2,
    rating: 4.7,
    reviewCount: 128,
    fabric: "Silk satin",
    care: ["Dry clean only", "Steam to remove creases"],
    measurements: [{ label: "Bust", value: "34in" }, { label: "Length", value: "52in" }],
    views: ["front", "back", "fabric"],
    imageUrls: {
      front: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=85",
      back: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=85",
      fabric: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=900&q=85",
    },
  },
  {
    id: "mock-navy-suit",
    name: "Classic Navy Three-Piece Suit",
    brand: "Common Thread",
    category: "Suits",
    occasions: ["Office", "Wedding"],
    styles: ["Formal", "Classic"],
    color: "Navy",
    colorHex: "#0F1D38",
    conditionCopy: "Tailored fit, dry-cleaned after every rental",
    currency: "INR",
    rentPrice: 2999,
    rentDays: 4,
    buyPrice: 18900,
    deposit: 2500,
    sizes: [
      { size: "38", available: true },
      { size: "40", available: true },
      { size: "42", available: true },
    ],
    availability: "available",
    availableFrom: "Today",
    deliveryDays: 2,
    rating: 4.8,
    reviewCount: 94,
    fabric: "Wool blend",
    care: ["Dry clean only"],
    measurements: [{ label: "Chest", value: "40in" }, { label: "Length", value: "30in" }],
    views: ["front", "back", "detail"],
    imageUrls: {
      front: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=900&q=85",
      back: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=85",
      detail: "https://images.unsplash.com/photo-1555069519-127aadedf1ee?auto=format&fit=crop&w=900&q=85",
    },
  },
  {
    id: "mock-emerald-gown",
    name: "Emerald Silk Wrap Gown",
    brand: "Maison Vale",
    category: "Dresses",
    occasions: ["Wedding", "Party"],
    styles: ["Formal", "Contemporary"],
    color: "Emerald",
    colorHex: "#1E3830",
    conditionCopy: "Excellent condition, inspected before dispatch",
    currency: "INR",
    rentPrice: 2299,
    rentDays: 4,
    buyPrice: 11500,
    deposit: 1500,
    sizes: [
      { size: "S", available: true },
      { size: "M", available: true },
      { size: "L", available: true },
    ],
    availability: "limited",
    availableFrom: "12 Sep",
    deliveryDays: 3,
    rating: 4.9,
    reviewCount: 61,
    fabric: "Silk crepe",
    care: ["Dry clean only", "Store on padded hanger"],
    measurements: [{ label: "Bust", value: "36in" }, { label: "Length", value: "58in" }],
    views: ["front", "back", "model"],
    imageUrls: {
      front: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=900&q=85",
      back: "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=900&q=85",
      model: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=900&q=85",
    },
  },
  {
    id: "mock-beige-blazer",
    name: "Beige Oversized Wool Blazer",
    brand: "Étoile",
    category: "Blazers",
    occasions: ["Office", "Everyday"],
    styles: ["Minimal", "Contemporary"],
    color: "Beige",
    colorHex: "#D3C3A6",
    conditionCopy: "Excellent condition, inspected before dispatch",
    currency: "INR",
    rentPrice: 1199,
    rentDays: 4,
    buyPrice: 5400,
    deposit: 800,
    sizes: [
      { size: "S", available: true },
      { size: "M", available: true },
      { size: "L", available: true },
    ],
    availability: "available",
    availableFrom: "Today",
    deliveryDays: 2,
    rating: 4.6,
    reviewCount: 73,
    fabric: "Wool blend",
    care: ["Dry clean only"],
    measurements: [{ label: "Chest", value: "38in" }, { label: "Length", value: "28in" }],
    views: ["front", "detail"],
    imageUrls: {
      front: "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=900&q=85",
      detail: "https://images.unsplash.com/photo-1559034750-cdab70a66b7c?auto=format&fit=crop&w=900&q=85",
    },
  },
  {
    id: "mock-black-blazer",
    name: "Black Evening Blazer",
    brand: "Common Thread",
    category: "Blazers",
    occasions: ["Party", "Date Night"],
    styles: ["Formal", "Classic"],
    color: "Black",
    colorHex: "#171A1F",
    conditionCopy: "Excellent condition, inspected before dispatch",
    currency: "INR",
    rentPrice: 1699,
    rentDays: 4,
    buyPrice: 7499,
    deposit: 1200,
    sizes: [
      { size: "36", available: true },
      { size: "38", available: true },
      { size: "40", available: false },
    ],
    availability: "available",
    availableFrom: "Today",
    deliveryDays: 2,
    rating: 4.7,
    reviewCount: 102,
    fabric: "Satin-trim wool",
    care: ["Dry clean only"],
    measurements: [{ label: "Chest", value: "39in" }, { label: "Length", value: "29in" }],
    views: ["front", "back"],
    imageUrls: {
      front: "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=900&q=85",
      back: "https://images.unsplash.com/photo-1539533113208-f6df8cc8b543?auto=format&fit=crop&w=900&q=85",
    },
  },
  {
    id: "mock-champagne-cocktail",
    name: "Champagne Sequin Cocktail Dress",
    brand: "Maison Vale",
    category: "Dresses",
    occasions: ["Party", "Festival"],
    styles: ["Street", "Contemporary"],
    color: "Champagne",
    colorHex: "#D9BE8E",
    conditionCopy: "Excellent condition, inspected before dispatch",
    currency: "INR",
    rentPrice: 2799,
    rentDays: 4,
    buyPrice: 9800,
    deposit: 1500,
    sizes: [
      { size: "XS", available: true },
      { size: "S", available: true },
    ],
    availability: "limited",
    availableFrom: "15 Sep",
    deliveryDays: 3,
    rating: 4.5,
    reviewCount: 47,
    fabric: "Sequin mesh",
    care: ["Dry clean only", "Do not steam directly"],
    measurements: [{ label: "Bust", value: "33in" }, { label: "Length", value: "34in" }],
    views: ["front", "fabric"],
    imageUrls: {
      front: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=85",
      fabric: "https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=900&q=85",
    },
  },
  {
    id: "mock-pinstripe-suit",
    name: "Charcoal Pinstripe Trouser Suit",
    brand: "Common Thread",
    category: "Suits",
    occasions: ["Office", "Wedding"],
    styles: ["Formal", "Traditional"],
    color: "Charcoal",
    colorHex: "#33363C",
    conditionCopy: "Tailored fit, dry-cleaned after every rental",
    currency: "INR",
    rentPrice: 2499,
    rentDays: 4,
    buyPrice: 16400,
    deposit: 2000,
    sizes: [
      { size: "S", available: true },
      { size: "M", available: true },
      { size: "L", available: true },
    ],
    availability: "available",
    availableFrom: "Today",
    deliveryDays: 2,
    rating: 4.6,
    reviewCount: 55,
    fabric: "Pinstripe wool",
    care: ["Dry clean only"],
    measurements: [{ label: "Bust", value: "35in" }, { label: "Length", value: "42in" }],
    views: ["front", "back"],
    imageUrls: {
      front: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=85",
      back: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=900&q=85",
    },
  },
  {
    id: "mock-dusty-rose-midi",
    name: "Dusty Rose Tulle Midi Dress",
    brand: "Maison Vale",
    category: "Dresses",
    occasions: ["Festival", "Date Night"],
    styles: ["Contemporary", "Street"],
    color: "Dusty Rose",
    colorHex: "#DDB9BC",
    conditionCopy: "Excellent condition, inspected before dispatch",
    currency: "INR",
    rentPrice: 1349,
    rentDays: 4,
    buyPrice: 5200,
    deposit: 900,
    sizes: [
      { size: "XS", available: true },
      { size: "S", available: true },
      { size: "M", available: true },
    ],
    availability: "available",
    availableFrom: "Today",
    deliveryDays: 2,
    rating: 4.8,
    reviewCount: 89,
    fabric: "Tulle overlay",
    care: ["Dry clean only", "Hang to store"],
    measurements: [{ label: "Bust", value: "34in" }, { label: "Length", value: "44in" }],
    views: ["front", "model"],
    imageUrls: {
      front: "https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=900&q=85",
      model: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=85",
    },
  },
];
